apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      # enabled: true
      paths:
        - "/log/*"
    fields:
      k8s-app: log-contanier-file-filebeat
    output.elasticsearch:
      hosts: ["elasticsearch-logging.logging:9200"]
      indices:
        - index: "filebeat-k8s-%{+YYYY.MM.dd}"
          default: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-contanier-file-filebeat
  labels:
    k8s-app: log-contanier-file-filebeat
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: log-contanier-file-filebeat
  template:
    metadata:
      labels:
        k8s-app: log-contanier-file-filebeat
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: log-contanier-file-filebeat
        image: alpine:latest
        command:
        - sh
        - -c
        - 'count=1;while true;do echo log to file $count>>/data/logs/log-contanier-file-filebeat.log;sleep 1;count=$(($count+1));done'
        volumeMounts:
        - name: app-logs
          mountPath: /data/logs
      - name: filebeat-logging
        image: registry.cn-shanghai.aliyuncs.com/k8s-log/filebeat:6.3.2
        volumeMounts:
        - name: app-logs
          mountPath: /log
        - name: filebeat-config
          mountPath: /usr/local/filebeat/config
      volumes:
      - name: app-logs
        emptyDir: {}
      - name: filebeat-config
        configMap:
          name: filebeat-config